### PR TITLE
(feat) Nextjs setup: init

### PR DESCRIPTION
**Pull request by pipesorter**
- Base nextjs
- Added typescript rel config.
- Added eslint (airbnb), prettier
- Basic folder structure with sample files for now

### CODE REVIEW

**Comment by sanathkr** [comment]
Why use `ui-new` folder instead of overwriting the `ui` folder?

**Comment by pipesorter** [comment]
@sanathkr In slack, I thought it was suggested to add in ui-new, will change it to `ui` and push.

**Comment by brettstack** [comment]
Yeah I was just suggesting to keep some of the work that exists in the current `ui` folder, namely, the Auth work in AuthenticatedApp.js

**Review by brettstack — APPROVED** [review]

**Pull request merged**
